### ISSUE TITLE
Alien spaceship should randomly reverse its direction

### ISSUE THREAD

**Issue by chrishic** [nicohman/flaming-octo-tribble#1]

**Comment by nicohman** [comment]
Like, multiple times, or just once per spaceship?

**Comment by chrishic** [comment]
once per spaceship — whenever it is in the middle half of the screen (i.e. if 100 pixels wide, 25 < x < 75 ), randomly determine if it should reverse its direction.  So two random triggers:  (1) decide whether it should reverse (say 1 of out 2 or 3), and (2) decide where reversal should happen.

**Comment by nicohman** [comment]
Alright then!
Working on it now

**Comment by nicohman** [comment]
And now they randomly switch
