### ISSUE TITLE
Sound effects should be synchronized with the event that triggers them

### ISSUE THREAD

**Issue by chrishic** [nicohman/flaming-octo-tribble#2]
right now, there is a HUGE latency between the event and the sound effect

**Comment by nicohman** [comment]
I can't seem to decrease latency anymore than I already have; I've made a dedicated audio element and everything, the audio element just doesn't want to start playing any faster...

**Comment by chrishic** [comment]
you’re pre-fetching the audio file, right?  and caching it in memory right?

**Comment by nicohman** [comment]
Yup. :-(

**Comment by nicohman** [comment]
I'll just close this, then. Reopen it if you have any ideas.

**Comment by nicohman** [comment]
This has now been solved!
