### ISSUE TITLE
Add concept of levels to game

### ISSUE THREAD

**Issue by chrishic** [nicohman/flaming-octo-tribble#7]
As levels increase, difficulty increases.  Need rules for what constitutes a level change (for example, you might need to destroy a certain number of flying objects to trigger a level up).

**Comment by nicohman** [comment]
Every 15 destroyed, level up & plane speed increases by a small amount?

**Comment by chrishic** [comment]
sounds like a good start — you’ll need to display level along with score now

**Comment by nicohman** [comment]
An done!
